import { describe, expect, it, vi } from "vitest";
import { createWorkspaceClient, type WorkspaceClientOptions } from "./wtsClient";
import { agentWorkItemIntegrationFixture } from "../test/agentWorkItemIntegrationFixture";
const preflight = agentWorkItemIntegrationFixture(); const request = { requestId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc", effectDigest: preflight.effectDigest };
const result = () => ({ schemaVersion: 1, workSetId: preflight.workSetId, taskId: preflight.taskId, workspaceId: preflight.workspaceId, repositoryId: preflight.repositoryId, integrationRequestId: request.requestId, state: "integrated", files: preflight.files, blockers: [], detail: "WTS applied the candidate." });
function transport(runtime: "http" | "tauri", value: unknown) { const fetch = vi.fn<typeof globalThis.fetch>().mockImplementation(async url => new Response(JSON.stringify(String(url).endsWith("/bootstrap") ? { sessionToken: "test" } : value), { status: 200, headers: { "Content-Type": "application/json" } })); const invoke = vi.fn(async () => value); return { fetch, invoke, client: createWorkspaceClient({ runtime, fetch, invoke: invoke as NonNullable<WorkspaceClientOptions["invoke"]> }) }; }
describe.each(["http", "tauri"] as const)("candidate integration over %s", runtime => {
  it("reads exact file effects without a mutation", async () => { const { client, fetch, invoke } = transport(runtime, preflight); await expect(client.preflightAgentWorkItemIntegration!(preflight.workSetId, preflight.taskId)).resolves.toEqual(preflight); if (runtime === "http") expect(fetch.mock.calls[1][0]).toBe(`/api/v1/agent-work-sets/${preflight.workSetId}/items/${preflight.taskId}/integration-preflight`); else expect(invoke).toHaveBeenCalledExactlyOnceWith("preflight_agent_work_item_integration", { workSetId: preflight.workSetId, taskId: preflight.taskId }); });
  it("sends and verifies the exact durable integration request", async () => { const { client, fetch, invoke } = transport(runtime, result()); await expect(client.integrateAgentWorkItem!(preflight.workSetId, preflight.taskId, request)).resolves.toEqual(result()); if (runtime === "http") expect(fetch.mock.calls[1]).toEqual([`/api/v1/agent-work-sets/${preflight.workSetId}/items/${preflight.taskId}/integration`, expect.objectContaining({ method: "POST", body: JSON.stringify(request) })]); else expect(invoke).toHaveBeenCalledExactlyOnceWith("integrate_agent_work_item", { workSetId: preflight.workSetId, taskId: preflight.taskId, request }); });
  it("retains the host continuation identity for incomplete file operations", async () => { const value = { ...preflight, resumeRequestId: request.requestId }; const { client } = transport(runtime, value); await expect(client.preflightAgentWorkItemIntegration!(preflight.workSetId, preflight.taskId)).resolves.toEqual(value); });
  it.each([
    ["no matching check", { ...preflight, checkRunIds: [] }], ["duplicate checks", { ...preflight, checkRunIds: [...preflight.checkRunIds, ...preflight.checkRunIds] }],
    ["ready with blockers", { ...preflight, blockers: [{ code: "drift", detail: "Files changed." }] }], ["wrong task", { ...preflight, taskId: request.requestId }],
    ["wrong set", { ...preflight, workSetId: request.requestId }], ["missing candidate", { ...preflight, candidateWorkspaceId: undefined }],
    ["bad digest", { ...preflight, effectDigest: "bad" }], ["parent traversal", { ...preflight, files: [{ filePath: "../secrets", status: "added" }] }],
    ["absolute path", { ...preflight, files: [{ filePath: "/tmp/file", status: "added" }] }], ["git metadata", { ...preflight, files: [{ filePath: ".git/config", status: "modified" }] }],
    ["duplicate files", { ...preflight, files: [...preflight.files, ...preflight.files] }], ["unsupported file status", { ...preflight, files: [{ filePath: "src/title.ts", status: "renamed" }] }],
    ["too many blockers", { ...preflight, blockers: Array.from({ length: 65 }, () => ({ code: "drift", detail: "Files changed." })) }],
    ["long detail", { ...preflight, detail: "é".repeat(1025) }], ["invalid resume ID", { ...preflight, resumeRequestId: "" }],
  ])("rejects %s before showing applicable file effects", async (_name, value) => { const { client } = transport(runtime, value); await expect(client.preflightAgentWorkItemIntegration!(preflight.workSetId, preflight.taskId)).rejects.toBeDefined(); });
  it.each([{ ...request, requestId: "" }, { ...request, effectDigest: "invalid" }, { ...request, files: preflight.files }])("rejects an invalid mutation before dispatch %#", async value => { const { client, fetch, invoke } = transport(runtime, result()); await expect(client.integrateAgentWorkItem!(preflight.workSetId, preflight.taskId, value)).rejects.toBeDefined(); expect(fetch).not.toHaveBeenCalled(); expect(invoke).not.toHaveBeenCalled(); });
  it.each(["integrated", "conflict", "incomplete"])("retains %s recovery facts", async state => { const value = { ...result(), state }; const { client } = transport(runtime, value); await expect(client.integrateAgentWorkItem!(preflight.workSetId, preflight.taskId, request)).resolves.toEqual(value); });
  it("rejects a response for another mutation", async () => { const { client } = transport(runtime, { ...result(), integrationRequestId: preflight.taskId }); await expect(client.integrateAgentWorkItem!(preflight.workSetId, preflight.taskId, request)).rejects.toBeDefined(); });
});
