import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { WorkspaceClient } from "../lib/wtsClient";
import { agentWorkSetFixture, WORK_SET_ID, WORK_TASK_ID } from "../test/agentWorkSetsFixture";
import { agentWorkItemIntegrationFixture } from "../test/agentWorkItemIntegrationFixture";
import { AgentWorkItemIntegration } from "./AgentWorkItemIntegration";
const set = agentWorkSetFixture(); const preflight = agentWorkItemIntegrationFixture();
function setup() { const client = { preflightAgentWorkItemIntegration: vi.fn().mockResolvedValue(preflight), integrateAgentWorkItem: vi.fn().mockImplementation(async (_set, _task, request) => ({ schemaVersion: 1, workSetId: WORK_SET_ID, taskId: WORK_TASK_ID, workspaceId: set.workspaceId, repositoryId: set.repositoryId, integrationRequestId: request.requestId, state: "integrated", files: preflight.files, blockers: [], detail: "WTS applied the candidate files." })) }; return { client, props: { client: client as unknown as WorkspaceClient, set, task: set.tasks[0], onLeaveReview: vi.fn() } }; }
async function open() { fireEvent.click(screen.getByText("Integrate candidate")); await screen.findByText("WTS can apply these candidate files."); }
beforeEach(() => localStorage.clear());
describe("candidate integration", () => {
  it("lists exact file effects and check evidence before the explicit apply", async () => { const { client, props } = setup(); render(<AgentWorkItemIntegration {...props} />); expect(client.preflightAgentWorkItemIntegration).not.toHaveBeenCalled(); await open(); expect(screen.getByText("src/title.ts")).toBeVisible(); expect(client.integrateAgentWorkItem).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Apply 1 file" })); await screen.findByText("WTS applied the candidate files."); expect(screen.queryByText("WTS can apply these candidate files.")).not.toBeInTheDocument(); expect(client.integrateAgentWorkItem).toHaveBeenCalledExactlyOnceWith(WORK_SET_ID, WORK_TASK_ID, expect.objectContaining({ effectDigest: preflight.effectDigest })); });
  it("offers the candidate verification workspace when checks block integration", async () => { const { client, props } = setup(); client.preflightAgentWorkItemIntegration.mockResolvedValue({ ...preflight, state: "blocked", checkRunIds: [], blockers: [{ code: "noChecks", detail: "Configure checks in candidate verification." }] }); const listener = vi.fn(); window.addEventListener("wts:open-agent-workspace", listener); render(<AgentWorkItemIntegration {...props} />); await open(); expect(screen.getByRole("button", { name: "Apply 1 file" })).toBeDisabled(); fireEvent.click(screen.getByRole("link", { name: "Open candidate verification" })); expect((listener.mock.calls[0][0] as CustomEvent).detail).toEqual({ workspaceId: set.tasks[0].workspaceId, repositoryId: set.tasks[0].repositoryId, tab: "verification" }); expect(props.onLeaveReview).toHaveBeenCalledOnce(); expect(client.integrateAgentWorkItem).not.toHaveBeenCalled(); window.removeEventListener("wts:open-agent-workspace", listener); });
  it("retains the exact uncertain apply across reload without another automatic write", async () => { const { client, props } = setup(); client.integrateAgentWorkItem.mockRejectedValueOnce(new Error("Connection lost.")); const view = render(<AgentWorkItemIntegration {...props} />); await open(); fireEvent.click(screen.getByRole("button", { name: "Apply 1 file" })); await screen.findByText("Connection lost."); const first = client.integrateAgentWorkItem.mock.calls[0]; view.unmount(); render(<AgentWorkItemIntegration {...props} />); await open(); expect(client.integrateAgentWorkItem).toHaveBeenCalledTimes(1); fireEvent.click(screen.getByRole("button", { name: "Retry integration request" })); await screen.findByText("WTS applied the candidate files."); expect(client.integrateAgentWorkItem.mock.calls[1]).toEqual(first); });
  it("continues an incomplete operation with the host request ID after storage is cleared", async () => { const { client, props } = setup(); client.preflightAgentWorkItemIntegration.mockResolvedValue({ ...preflight, resumeRequestId: WORK_TASK_ID }); render(<AgentWorkItemIntegration {...props} />); await open(); expect(client.integrateAgentWorkItem).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Continue integration" })); await screen.findByText("WTS applied the candidate files."); expect(client.integrateAgentWorkItem).toHaveBeenCalledExactlyOnceWith(WORK_SET_ID, WORK_TASK_ID, { requestId: WORK_TASK_ID, effectDigest: preflight.effectDigest }); });
  it("retains incomplete file effects and the same retry payload", async () => { const { client, props } = setup(); client.integrateAgentWorkItem.mockImplementationOnce(async (_set, _task, request) => ({ schemaVersion: 1, workSetId: WORK_SET_ID, taskId: WORK_TASK_ID, workspaceId: set.workspaceId, repositoryId: set.repositoryId, integrationRequestId: request.requestId, state: "incomplete", files: preflight.files, blockers: [], detail: "One file remains." })); render(<AgentWorkItemIntegration {...props} />); await open(); fireEvent.click(screen.getByRole("button", { name: "Apply 1 file" })); await screen.findByText("One file remains."); const first = client.integrateAgentWorkItem.mock.calls[0]; fireEvent.click(screen.getByRole("button", { name: "Retry integration request" })); await screen.findByText("WTS applied the candidate files."); expect(client.integrateAgentWorkItem.mock.calls[1]).toEqual(first); });
  it("rejects a preflight for another candidate before enabling apply", async () => { const { client, props } = setup(); client.preflightAgentWorkItemIntegration.mockResolvedValue({ ...preflight, candidateAfterCheckpointId: WORK_TASK_ID }); render(<AgentWorkItemIntegration {...props} />); fireEvent.click(screen.getByText("Integrate candidate")); await screen.findByText(/do not match this candidate/); expect(screen.queryByRole("button", { name: "Apply 1 file" })).not.toBeInTheDocument(); expect(client.integrateAgentWorkItem).not.toHaveBeenCalled(); });
  it("refuses a write when durable mutation storage fails", async () => { const { client, props } = setup(); render(<AgentWorkItemIntegration {...props} />); await open(); const spy = vi.spyOn(Storage.prototype, "setItem").mockImplementation(() => { throw new Error("Full."); }); fireEvent.click(screen.getByRole("button", { name: "Apply 1 file" })); await screen.findByText(/Check browser storage/); expect(client.integrateAgentWorkItem).not.toHaveBeenCalled(); spy.mockRestore(); });
});
