import { fireEvent, render, screen, within } from '@testing-library/react';
import { describe, expect, it, beforeEach } from 'vitest';
import { AgentLab } from './AgentLab';
import { descendants, initialExecutions, metrics, stopExecutions, type Execution } from './model';
beforeEach(()=>{location.hash=''; Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(this:HTMLDialogElement){this.setAttribute('open','');}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(this:HTMLDialogElement){this.removeAttribute('open');}});});
describe('agent design lab',()=>{
 it('counts parallel agents separately from elapsed time without adding parent subtree totals',()=>{const list=initialExecutions('team');expect(metrics(list)).toMatchObject({total:77,elapsed:30,peak:4,working:3,questions:1});expect(metrics([...list,list[0]])).toEqual(metrics(list));expect(descendants(list,'qa')).toEqual(['qa','browser']);});
 it('calculates the three-agent example and excludes the waiting coordinator',()=>{const base=initialExecutions('team')[0];const list:Execution[]=[{...base,intervals:[]},...[1,2,3].map(i=>({...base,id:String(i),parent:base.id,intervals:[[0,20]] as [number,number][]}))];expect(metrics(list)).toMatchObject({total:60,elapsed:20,parallelism:3,peak:3});});
 it('stops only the selected execution unless descendant scope is explicit',()=>{const list=initialExecutions('team');expect(stopExecutions(list,'qa',false).find(a=>a.id==='browser')?.state).toBe('working');expect(stopExecutions(list,'qa',true).find(a=>a.id==='browser')?.state).toBe('stopped');expect(stopExecutions(list,'qa',true).find(a=>a.id==='ui')?.state).toBe('working');});
 it('opens a question, requires a response, and clears it from the inbox',()=>{render(<AgentLab/>);fireEvent.click(screen.getByRole('button',{name:/1 decision needs you/}));expect(screen.getByRole('button',{name:'Send demo response'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Use suggested response'}));fireEvent.click(screen.getByRole('button',{name:'Send demo response'}));expect(screen.getByRole('status')).toHaveTextContent('Nothing was sent');fireEvent.click(screen.getByRole('button',{name:'Needs you 0'}));expect(screen.getByRole('heading',{name:'You’re clear.'})).toBeVisible();});
 it('collapses nested workers and keeps matched children visible while filtering',()=>{render(<AgentLab/>);fireEvent.click(screen.getByRole('button',{name:'Collapse Workspace setup'}));expect(screen.queryByRole('button',{name:/URL → services → ready/})).not.toBeInTheDocument();fireEvent.change(screen.getByRole('textbox',{name:'Find an agent'}),{target:{value:'Browser'}});expect(screen.getByRole('button',{name:/URL → services → ready/})).toBeVisible();});
 it('handles a failed child with a scoped retry',()=>{render(<AgentLab/>);fireEvent.change(screen.getByRole('combobox',{name:'Demo scenario'}),{target:{value:'failure'}});fireEvent.click(screen.getByRole('button',{name:/URL → services → ready Browser/}));fireEvent.click(screen.getByRole('button',{name:'Retry in demo'}));expect(screen.getByRole('status')).toHaveTextContent('No browser task was launched');expect(screen.queryByRole('button',{name:'Retry in demo'})).not.toBeInTheDocument();});
 it('exposes empty state, busy filtering, history, and metric navigation',()=>{render(<AgentLab/>);fireEvent.change(screen.getByRole('combobox',{name:'Demo scenario'}),{target:{value:'empty'}});expect(screen.getByRole('heading',{name:'Your next team starts here.'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Load the team demo'}));fireEvent.change(screen.getByRole('combobox',{name:'Demo scenario'}),{target:{value:'busy'}});fireEvent.change(screen.getByRole('textbox',{name:'Find an agent'}),{target:{value:'Verify model picker 3'}});expect(screen.getByRole('button',{name:/Verify model picker 3/})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Time & capacity'}));expect(screen.getByText('Total agent work')).toBeVisible();expect(screen.getByRole('button',{name:/URL → services → ready, 18 minutes/})).toBeVisible();});
 it('pins a workspace and opens a review draft without posting',()=>{render(<AgentLab/>);fireEvent.click(screen.getByRole('button',{name:'Spaces'}));const pin=screen.getByRole('button',{name:'Pin wts-ui'});expect(pin).toHaveAttribute('aria-pressed','true');fireEvent.click(pin);expect(pin).toHaveAttribute('aria-pressed','false');fireEvent.click(screen.getByRole('button',{name:'Open workspace'}));fireEvent.click(screen.getByRole('button',{name:'Review changes'}));fireEvent.click(screen.getByRole('button',{name:'Save comment draft'}));expect(screen.getByRole('status')).toHaveTextContent('Nothing was posted to GitLab');});
 it('keeps a response scoped to its workspace across switches',()=>{render(<AgentLab/>);fireEvent.click(screen.getByRole('button',{name:/1 decision needs you/}));fireEvent.click(screen.getByRole('button',{name:'Use suggested response'}));fireEvent.click(screen.getByRole('button',{name:'Send demo response'}));fireEvent.click(screen.getByRole('button',{name:/A\s*fleet-status/}));expect(screen.getByRole('button',{name:'Needs you 1'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:/W\s*wts-ui/}));expect(screen.getByRole('button',{name:'Needs you 0'})).toBeVisible();});
 it('confirms stopping descendants and leaves other work alone',()=>{render(<AgentLab/>);fireEvent.click(screen.getByRole('button',{name:/Verify desktop flow Test coordinator/}));fireEvent.click(screen.getByRole('button',{name:'Stop…'}));const dialog=screen.getByRole('dialog');fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(within(dialog).getByRole('button',{name:'Stop team in demo'}));expect(screen.getByRole('button',{name:'Stop…'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:/Repository URL flow Implementation/}));expect(screen.getByRole('button',{name:'Stop…'})).toBeEnabled();});
});
