import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { Glyph } from '../variants/local-workspace/Glyph';
import { initialExecutions, workspaceExecutions, metrics, descendants, stopExecutions, stateLabels, type Execution, type Scenario } from './model';
type View = 'workspace'|'spaces'|'timeline'|'inbox';
const references = [
 ['Cursor','https://cursor.com/docs/subagents','Show the worker, its model, and its task.'],
 ['Claude Code','https://code.claude.com/docs/en/agent-teams','Inspect one worker without losing the team.'],
 ['Linear','https://linear.app/docs/inbox','Keep decisions separate from background updates.'],
 ['Langfuse','https://langfuse.com/faq/all/what-does-a-good-trace-look-like','Make parent and child activity inspectable.'],
 ['Dribbble · Excited','https://dribbble.com/shots/27561937-AI-Agent-Management-Dashboard','Compact status, restrained accents, clear actions.'],
 ['Dribbble · AgentOps','https://dribbble.com/shots/27664692-AgentOps-Web-Template','Explore consistent navigation and operational density.'],
 ['Antigravity','https://antigravity.google/blog/introducing-google-antigravity','Move between workspaces and review results.'],
 ['GitHub Actions','https://docs.github.com/en/actions/how-tos/monitor-workflows/use-the-visualization-graph','Expose dependencies and failed steps.'],
];
const ownTime = (a: Execution) => a.intervals.reduce((sum,[s,e])=>sum+e-s,0);
export function AgentLab() {
 const [view,setView] = useState<View>(()=>(['workspace','spaces','timeline','inbox'].includes(location.hash.slice(1)) ? location.hash.slice(1) : 'workspace') as View);
 const [scenario,setScenario]=useState<Scenario>('team');
 const [agents,setAgents]=useState(()=>initialExecutions('team'));
 const [selected,setSelected]=useState('lead');
 const [expanded,setExpanded]=useState(new Set(['lead','qa']));
 const [filter,setFilter]=useState('all');
 const [query,setQuery]=useState('');
 const [detailTab,setDetailTab]=useState('overview');
 const [answer,setAnswer]=useState('');
 const [notice,setNotice]=useState('');
 const [dialog,setDialog]=useState<'sources'|'stop'|null>(null);
 const [stopTree,setStopTree]=useState(false);
 const [light,setLight]=useState(false);
 const [workspace,setWorkspace]=useState('wts-ui');
 const workspaceRuns=useRef<Record<string,Execution[]>>({});
 function selectWorkspace(name:string,selectedId='lead'){workspaceRuns.current[workspace]=agents;setAgents(workspaceRuns.current[name]??workspaceExecutions(name,scenario));setWorkspace(name);setSelected(selectedId);setFilter('all');setQuery('');setDetailTab('overview');setAnswer('');navigate('workspace');}
 const [pinned,setPinned]=useState(new Set(['wts-ui']));
 const dialogRef=useRef<HTMLDialogElement>(null);
 const returnFocus=useRef<HTMLElement|null>(null);
 const m=metrics(agents); const agent=agents.find(a=>a.id===selected) ?? agents[0];
 const attention=agents.filter(a=>a.state==='question'||a.state==='failed');
 function navigate(next: View){setView(next);location.hash=next;}
 function choose(a: Execution){setSelected(a.id);setDetailTab('overview');setAnswer('');}
 function openDialog(next: 'sources'|'stop'){returnFocus.current=document.activeElement as HTMLElement;setDialog(next);}
 function closeDialog(){setDialog(null);}
 function reset(next: Scenario=scenario){setScenario(next);workspaceRuns.current={};setAgents(workspaceExecutions(workspace,next));setExpanded(new Set(['lead','qa']));setSelected('lead');setFilter('all');setQuery('');setDetailTab('overview');setNotice('Demo reset. No real agents were changed.');}
 useEffect(()=>{if(dialog)dialogRef.current?.showModal();else {dialogRef.current?.close();returnFocus.current?.focus();}},[dialog]);
 useEffect(()=>{const fn=()=>setView((['workspace','spaces','timeline','inbox'].includes(location.hash.slice(1))?location.hash.slice(1):'workspace') as View);window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 function respond(){if(!answer.trim()||!agent)return;setAgents(list=>list.map(a=>a.id===agent.id?{...a,state:'working',summary:'Your response is attached to this demo task. The review can continue.'}:a));setNotice('Response added to the demo. Nothing was sent to an agent.');setAnswer('');}
 function visible(a: Execution){return (!query || (a.title+' '+a.role+' '+a.model).toLowerCase().includes(query.toLowerCase())) && (filter==='all'||(filter==='attention'?(a.state==='question'||a.state==='failed'):a.state==='working'));}
 function agentRow(a: Execution,depth=0): React.ReactNode {const children=agents.filter(x=>x.parent===a.id);const match=visible(a);const childMatch=descendants(agents,a.id).some(id=>visible(agents.find(x=>x.id===id)!));if(!match&&!childMatch)return null;const forced=!!query||filter!=='all';return <li key={a.id}>
   <div className={'agent-row '+(agent?.id===a.id?'selected':'')} style={{'--depth':depth} as CSSProperties}>
    {children.length?<button className={'disclosure '+(expanded.has(a.id)||forced?'open':'')} aria-label={(expanded.has(a.id)?'Collapse ':'Expand ')+a.title} aria-expanded={expanded.has(a.id)||forced} disabled={forced} onClick={()=>setExpanded(old=>{const n=new Set(old);n.has(a.id)?n.delete(a.id):n.add(a.id);return n;})}><Glyph name="arrow" size={12}/></button>:<span className="tree-stem"/>}
    <button className="agent-select" onClick={()=>choose(a)} aria-pressed={agent?.id===a.id} aria-label={`${a.title} ${a.role} · ${stateLabels[a.state]} · ${ownTime(a)}m`}><span title={stateLabels[a.state]} className={'state-mark '+a.state}>{a.state==='done'?<Glyph name="check" size={11}/>:null}</span><span><strong>{a.title}</strong><small>{a.role} {children.length?`· ${children.length} ${children.length===1?'worker':'workers'}`:''}</small></span><span className="row-minutes">{ownTime(a)}m</span></button>
   </div>{children.length&&(expanded.has(a.id)||forced)?<ul>{children.map(c=>agentRow(c,depth+1))}</ul>:null}
  </li>;}
 const teamIds=agent?descendants(agents,agent.id):[];
 const selectedTotal=agents.filter(a=>teamIds.includes(a.id)).reduce((s,a)=>s+ownTime(a),0);
 return <div className={'lab '+(light?'light':'')}>
  <div className="preview-bar"><span><b>DESIGN LAB</b><span className="preview-note">Simulated activity · no real tasks run</span></span><div><label>Scenario <select aria-label="Demo scenario" value={scenario} onChange={e=>reset(e.target.value as Scenario)}><option value="team">6 agents · one question</option><option value="busy">20 agents · busy workspace</option><option value="failure">Failed browser check</option><option value="empty">No agents yet</option></select></label><button onClick={()=>reset()} title="Reset demo"><Glyph name="refresh" size={13}/><span>Reset</span></button><button onClick={()=>openDialog('sources')}>Research <Glyph name="external" size={12}/></button></div></div>
  <div className="shell">
   <aside className="sidebar" data-ui="agent-lab.navigation" data-ui-label="Design lab navigation"><div className="brand"><span className="brand-icon"><Glyph name="branch" size={19}/></span><b>WTS</b><span className="personal">Personal</span></div>
    <nav aria-label="Main navigation"><button className={view==='spaces'?'active':''} onClick={()=>navigate('spaces')}><Glyph name="folder"/>Spaces</button><button className={view==='inbox'?'active':''} onClick={()=>navigate('inbox')}><Glyph name="comment"/>Needs you <span className="nav-count">{attention.length}</span></button><button className={view==='timeline'?'active':''} onClick={()=>navigate('timeline')}><Glyph name="branch"/>Time & capacity</button></nav>
    <div className="nav-label">WORKSPACES <span>3</span></div><nav aria-label="Workspaces">{['wts-ui','operation: kill senzu','asset-status'].map((name,i)=><button key={name} className={view==='workspace'&&workspace===name?'active workspace-link':'workspace-link'} onClick={()=>{selectWorkspace(name);}}><span className={'workspace-symbol symbol-'+i}>{['W','S','A'][i]}</span><span>{name}</span>{name==='wts-ui'&&<span className="tiny-dot"/>}</button>)}</nav>
    <div className="sidebar-bottom"><div className="connection"><span className="tiny-dot"/> Local design preview</div><p>Real workspace names.<br/>Illustrative agent runs.</p><button onClick={()=>setLight(!light)}><Glyph name={light?'moon':'sun'}/>{light?'Dark appearance':'Light appearance'}</button><span className="avatar">NH</span><span>Nandan <small>Local workspace</small></span></div>
   </aside>
   <main>
    <header className="topbar"><span className="breadcrumb">Personal <Glyph name="arrow" size={11}/> {view==='workspace'?workspace: view==='spaces'?'Spaces':view==='inbox'?'Needs you':'Time & capacity'}</span><span className="preview-pill">INTERACTIVE PROTOTYPE</span></header>
    <div className="page-heading"><div className="eyebrow">{view==='workspace'?'WORKSPACE / AGENT TEAM':view==='spaces'?'YOUR WORK, IN PARALLEL':view==='inbox'?'DECISIONS, NOT NOTIFICATIONS':'WORKSPACE / MEASURED ACTIVITY'}</div><div className="heading-row"><div><h1>{view==='workspace'?workspace:view==='spaces'?'A place for every workstream.':view==='inbox'?'Keep the work moving.':'More agents. Clearer accounting.'}</h1><p>{view==='workspace'?'Repository setup · 1 coordinated task · independent work stays separate':view==='spaces'?'See what is moving, what needs you, and what is ready to review.':view==='inbox'?'Questions and failed steps, with enough context to act.':'Agent work and elapsed time answer different questions.'}</p></div>{view==='workspace'&&<button className="primary" onClick={()=>{setDetailTab('changes');}}><Glyph name="code"/>Review changes</button>}</div></div>
    {view==='workspace'&&<>
     <div className="workspace-tabs"><span className="current">Agents <b>{agents.length}</b></span><button onClick={()=>navigate('timeline')}>Timeline</button><button onClick={()=>{setDetailTab('changes');}}>Changes <b>1</b></button><span className="branch"><Glyph name="branch" size={13}/>ui/workspace-setup</span></div>
     <div className="metrics-inline"><span><i className="tiny-dot"/><b>{m.working}</b> working</span><button onClick={()=>{setFilter('attention');if(attention[0])choose(attention[0]);}}><i className="tiny-dot amber"/><b>{attention.length}</b> {attention.length===1?'needs':'need'} you</button><span title="Own work summed across unique agents. Waiting is excluded."><b>{m.total}m</b> agent work</span><span title="Time covered by at least one agent. Parallel activity is counted once."><b>{m.elapsed}m</b> elapsed</span><span className="live-note">Demo snapshot · 10:30</span></div>
     {!agents.length?<div className="empty-state"><Glyph name="branch" size={32}/><h2>Your next team starts here.</h2><p>When an agent delegates work, its workers appear under the task.</p><button className="primary" onClick={()=>reset('team')}>Load the team demo</button></div>:<div className="workbench">
      <section className="agent-list" aria-label="Agent hierarchy" data-ui="agent-lab.hierarchy" data-ui-label="Agent hierarchy"><div className="section-label">AGENTS <span>{agents.length} in this workspace</span></div><label className="search"><Glyph name="search" size={14}/><input aria-label="Find an agent" placeholder="Find an agent or task" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filter-row">{[['all','All'],['working','Working'],['attention','Needs you']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><ul className="hierarchy">{agents.filter(a=>!a.parent).map(a=>agentRow(a))}</ul>{!agents.some(visible)&&<p className="filter-empty">No agents match.<button onClick={()=>{setQuery('');setFilter('all');}}>Clear filters</button></p>}<div className="hierarchy-note"><Glyph name="branch" size={14}/><span>Nested rows are delegated work.<br/>Times show each agent’s own work.</span></div></section>
      {agent&&<section className="agent-detail" data-ui="agent-lab.detail" data-ui-label="Selected agent"><div className="detail-heading"><div className="detail-role">{agent.role} <span> / {agent.parent?'Delegated by '+agents.find(a=>a.id===agent.parent)?.title:'Root task'}</span></div><div className="detail-title"><h2>{agent.title}</h2><span className={'status '+agent.state}><span className={'state-mark '+agent.state}/>{stateLabels[agent.state]}</span></div><div className="agent-meta"><span><Glyph name="terminal" size={13}/>{agent.provider}</span><code>{agent.model}</code><span>Own work {ownTime(agent)}m</span>{teamIds.length>1&&<span>Team total {selectedTotal}m</span>}</div></div>
       <div className="detail-tabs" aria-label="Agent detail view">{['overview','activity','changes'].map(tab=><button key={tab} aria-pressed={detailTab===tab} onClick={()=>setDetailTab(tab)}>{tab==='overview'?'Overview':tab==='activity'?'Activity log':'Changes & review'}</button>)}</div>
       <div className="detail-content">{detailTab==='overview'?<>
        <div className="summary"><span className="section-label">LATEST UPDATE</span><p>{agent.summary}</p></div>
        {agent.state==='question'?<div className="decision"><span className="decision-label"><Glyph name="comment" size={15}/>DECISION NEEDED</span><h3>Should maintenance tasks start automatically?</h3><p>The detected task can change remote state. I suggest listing it as an optional service.</p><div className="decision-context"><code>runtime_analysis.rs:184</code><span>Review rule · explicit side effects</span></div><label htmlFor="decision-answer">Your response</label><textarea id="decision-answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Keep it optional. Show its effect before launch."/><div className="decision-actions"><button onClick={()=>setAnswer('Keep maintenance tasks optional. Show their effect before launch.')}>Use suggested response</button><button className="primary" disabled={!answer.trim()} onClick={respond}>Send demo response <Glyph name="arrow" size={13}/></button></div><small>Preview only. No message leaves this page.</small></div>:agent.state==='failed'?<div className="failure-box"><Glyph name="warning"/><h3>The browser check did not finish.</h3><p>The services step timed out. Review the failed step before retrying.</p><code>workspace-setup.spec.ts:62 · timeout after 30s</code><button className="primary" onClick={()=>{setAgents(list=>list.map(a=>a.id===agent.id?{...a,state:'working',summary:'Retry started in the demo. The failed attempt remains in history.'}:a));setNotice('Demo retry started. No browser task was launched.');}}>Retry in demo</button></div>:<>
         {agent.id==='lead'&&attention.length>0&&<button className="attention-callout" onClick={()=>choose(attention[0])}><span className="callout-icon"><Glyph name="comment" size={19}/></span><span><strong>{attention.length} {attention.length===1?'decision needs':'decisions need'} you</strong><small>{attention[0].state==='failed'?'A browser check failed. Inspect the result.':'Review agent asks about automatic service startup.'}</small></span><Glyph name="arrow" size={17}/></button>}
         <div className="work-steps"><div className="section-label">RESULTS & NEXT STEPS</div>{[['done','Repository URL accepted','The URL field and repository picker share one flow.'],['working','Detect runnable services','Check entry points before showing launch controls.'],['waiting','Review and verify','Finish the review and browser checks before marking ready.']].map(([state,title,body])=><div className="work-step" key={title}><span className={'step-icon '+state}>{state==='done'?<Glyph name="check" size={13}/>:<span className={'state-mark '+state}/>}</span><div><strong>{title}</strong><p>{body}</p></div></div>)}</div>
         <button className="artifact" onClick={()=>setDetailTab('changes')}><span className="artifact-icon"><Glyph name="code" size={22}/></span><span><strong>Repository setup changes</strong><small>1 file · 1 review question · illustrative diff</small></span><span className="diff-count">+2 −1</span><Glyph name="arrow" size={15}/></button>
        </>}
       </>:detailTab==='activity'?<><div className="section-label">RECORDED ACTIONS <span>No hidden reasoning</span></div><ol className="activity-log">{[['10:30','Status',stateLabels[agent.state]],['10:26','Review','Checked the service startup behavior.'],['10:18','Tool','Read '+agent.file],['10:12','Task','Received the task and workspace context.'],['10:00','Started','Recorded this execution and its parent link.']].map(([time,type,text])=><li key={time}><time>{time}</time><span className="log-line"/><div><strong>{type}</strong><p>{text}</p></div></li>)}</ol><p className="muted">This log illustrates visible actions and status updates. The production view will use provider events.</p></>:<><div className="diff-heading"><code>runtime_analysis.rs</code><span className="diff-count">+2 −1</span></div><div className="diff"><div><span>181</span><code> fn detect_services(repo: &Repository) {'{'}</code></div><div className="removed"><span>182</span><code>−  service.auto_start = true;</code></div><div className="added"><span>182</span><code>+  service.auto_start = false;</code></div><div className="added"><span>183</span><code>+  service.requires_confirmation = true;</code></div><div><span>184</span><code> {'}'}</code></div></div><div className="inline-comment"><div><span className="avatar small">R</span><strong>Raptik review</strong><span className="status question">Question</span></div><p>Keep remote maintenance tasks opt-in. Can we show the effect before the user starts this service?</p><button onClick={()=>{setNotice('Comment saved as a demo draft. Nothing was posted to GitLab.');}}>Save comment draft</button><small>GitLab posting would be a separate reviewed action.</small></div></>}
       </div><footer className="detail-footer"><span><Glyph name="folder" size={13}/>{workspace}<span className="footer-dot">·</span>Read-only preview</span><button disabled={agent.state==='stopped'||agent.state==='done'} onClick={()=>{setStopTree(false);openDialog('stop');}}><Glyph name="stop" size={12}/>Stop…</button></footer>
      </section>}
     </div>}
    </>}
    {view==='spaces'&&<div className="spaces-view"><div className="board-summary"><span><i className="tiny-dot"/> {m.working} working across this demo</span><button onClick={()=>navigate('inbox')}>{attention.length} need your input <Glyph name="arrow" size={12}/></button></div><div className="board">{['Working','Needs you','Ready to review'].map((column,i)=><section key={column}><h2><i className={'tiny-dot '+(i===1?'amber':i===2?'blue':'')}/>{column}<span>1</span></h2><article className="workspace-card"><div className="card-top"><span className={'workspace-symbol symbol-'+i}>{['W','A','S'][i]}</span><button aria-label={'Pin '+['wts-ui','asset-status','operation: kill senzu'][i]} aria-pressed={pinned.has(['wts-ui','asset-status','operation: kill senzu'][i])} onClick={()=>setPinned(old=>{const next=new Set(old);const name=['wts-ui','asset-status','operation: kill senzu'][i];next.has(name)?next.delete(name):next.add(name);return next;})}><Glyph name="pin" size={15}/></button></div><h3>{['wts-ui','asset-status','operation: kill senzu'][i]}</h3><p>{['Make workspace setup predictable','Choose which services can start','Review the provisioning changes'][i]}</p><div className="card-team"><span className="avatar small">C</span><span>{[`${m.working} working · ${agents.length} agents`,'1 question · review agent','3 results · checks finished'][i]}</span></div><div className="card-preview">{['URL flow','Startup policy','Review ready'][i]}<span>{['Implementation','Needs a decision','Results'][i]}</span></div><button className="card-link" onClick={()=>{selectWorkspace(['wts-ui','asset-status','operation: kill senzu'][i],i===1?'review':'lead');}}>{i===1?'Answer question':i===2?'Inspect results':'Open workspace'}<Glyph name="arrow" size={14}/></button></article><p className="column-hint">{['Independent agents stay inside their workspace.','A question stays visible until you answer it.','Finished work links to evidence, not just a status.'][i]}</p></section>)}</div></div>}
    {view==='inbox'&&<section className="inbox-view">{attention.length?attention.map(a=><button className="inbox-item" key={a.id} onClick={()=>{choose(a);navigate('workspace');}}><span className={'state-mark '+a.state}/><span><strong>{a.title}</strong><p>{a.state==='question'?'Should maintenance tasks start automatically?':'The browser check timed out. Review the failed step.'}</p><small>{workspace} / {a.role}</small></span><span className={'status '+a.state}>{stateLabels[a.state]}</span><Glyph name="arrow"/></button>):<div className="empty-state"><Glyph name="check" size={32}/><h2>You’re clear.</h2><p>No demo agents need a decision.</p><button onClick={()=>navigate('workspace')}>Back to workspace</button></div>}</section>}
    {view==='timeline'&&<section className="time-view" data-ui="agent-lab.timeline" data-ui-label="Agent capacity timeline"><div className="time-kpis">{[[m.total+'m','Total agent work','Own work, added across agents'],[m.elapsed+'m','Elapsed time','Parallel work counted once'],[m.parallelism.toFixed(1)+'×','Parallelism','Agent time ÷ elapsed time'],[m.peak.toString(),'Peak concurrency','Most agents working together']].map(([value,label,help])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{help}</small></div>)}</div><div className="timeline-card"><header><div><h2>Who worked, and when</h2><p>{workspace} · illustrative 30-minute window</p></div><span className="status waiting">10:00–10:30</span></header><div className="timeline-scroll"><div className="timeline-axis"><span>EXECUTION</span><div>{['10:00','10:05','10:10','10:15','10:20','10:25','10:30'].map(t=><span key={t}>{t}</span>)}</div><span>OWN TIME</span></div><div className="timeline-row human"><strong>You <small>ActivityWatch example</small></strong><div className="track"><span style={{left:'0%',width:'33.33%'}} title="User active · 10:00–10:10"/><span style={{left:'56.66%',width:'26.67%'}} title="User active · 10:17–10:25"/></div><code>18m</code></div>{agents.map(a=><div className="timeline-row" key={a.id}><button onClick={()=>{choose(a);navigate('workspace');}}>{a.parent&&<Glyph name="branch" size={12}/>}<span>{a.title}<small>{a.role}</small></span></button><div className="track">{a.intervals.map(([s,e],i)=><button key={i} className={a.state} style={{left:s/30*100+'%',width:(e-s)/30*100+'%'}} aria-label={`${a.title}, ${e-s} minutes, 10:${String(s).padStart(2,'0')} to 10:${String(e).padStart(2,'0')}`} title={`${a.title} · ${e-s}m own work · ${a.file}`} onClick={()=>{choose(a);navigate('workspace');}}/>)}</div><code>{ownTime(a)}m</code></div>)}<div className="concurrency-row"><span>Concurrent agents</span><div>{m.segments.map((n,i)=><i key={i} style={{height:Math.max(3,n/Math.max(1,m.peak)*48)}} title={`${n} agents at 10:${String(i).padStart(2,'0')}`}/>)}</div><code>{m.peak} max</code></div></div></div><div className="metric-explainer"><Glyph name="help" size={20}/><div><h3>{m.total} minutes of agent work happened within {m.elapsed} minutes.</h3><p>Waiting coordinators add no own-work time while their children run. Parallelism measures concurrency, not output quality or human speed.</p><span>Usage and cost: <b>not reported</b> in this preview.</span></div></div></section>}
   </main>
  </div>
  {notice&&<div className="notice" role="status"><Glyph name="check" size={15}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><Glyph name="close" size={13}/></button></div>}
  <dialog ref={dialogRef} className="lab-dialog" onCancel={e=>{e.preventDefault();closeDialog();}} onClick={e=>{if(e.target===e.currentTarget)closeDialog();}} aria-label={dialog==='sources'?'Research and design decisions':'Stop demo execution'}><div className="dialog-head"><h2>{dialog==='sources'?'Research behind the design':'Stop this execution?'}</h2><button aria-label="Close dialog" onClick={closeDialog}><Glyph name="close"/></button></div>{dialog==='sources'?<><p>These are design references, not claims that WTS already supports their features.</p><div className="source-list">{references.map(([label,url,reason])=><a key={label} href={url} target="_blank" rel="noreferrer"><strong>{label}<Glyph name="external" size={13}/></strong><span>{reason}</span></a>)}</div><div className="recommendation"><b>Recommendation</b><p>Use the workspace and task as the main context. Reveal the agent tree and traces only when the user needs them.</p></div></>:<><p><b>{agent?.title}</b> will stop in this demo.</p>{teamIds.length>1?<label className="stop-choice"><input type="checkbox" checked={stopTree} onChange={e=>setStopTree(e.target.checked)}/>Also stop its {teamIds.length-1} descendant agents</label>:<p>This execution has no children.</p>}<p className="muted">{stopTree?'The selected coordinator and its descendants will stop.':'Other agents will keep their current state.'} No real process is affected.</p><div className="dialog-actions"><button onClick={closeDialog}>Keep working</button><button className="danger" onClick={()=>{if(agent)setAgents(list=>stopExecutions(list,agent.id,stopTree));closeDialog();setNotice('Stopped in the demo only. No real agent was stopped.');}}>Stop {stopTree?'team':'execution'} in demo</button></div></>}</dialog>
 </div>;
}
