import type { Page } from "@playwright/test";
import type { AgentWorkSet, CreateAgentWorkSetRequest } from "../src/lib/agentWorkSets";
import { agentTurnChangesFixture } from "../src/test/agentTurnChangesFixture";
import { agentTurnDecisionsFixture } from "../src/test/agentTurnDecisionsFixture";
import { agentWorkChildFixture, agentWorkSetFixture } from "../src/test/agentWorkSetsFixture";
import { MR_CONVERSATION, UNRELATED_DRAFT, expect, mountFeedback, test } from "./fixtures/agentFeedback";
const receipt = agentTurnChangesFixture({ conversationId: MR_CONVERSATION, repositoryId: "repo-original-mr", workspaceId: "11111111-1111-4111-8111-111111111111", requestId: "99999999-9999-4999-8999-999999999999" });
async function plans(page: Page, loseOnce = false) {
  const sets: AgentWorkSet[] = []; const creates: CreateAgentWorkSetRequest[] = []; const cancels: unknown[] = []; let lost = false;
  await page.route("**/api/v1/agent-conversations/*/messages/*/work-sets", async route => {
    expect(new URL(route.request().url()).pathname).toBe(`/api/v1/agent-conversations/${receipt.conversationId}/messages/${receipt.requestId}/work-sets`);
    if (route.request().method() === "GET") return route.fulfill({ json: { schemaVersion: 1, conversationId: receipt.conversationId, requestId: receipt.requestId, workSets: sets } });
    const request = route.request().postDataJSON() as CreateAgentWorkSetRequest; creates.push(request);
    let set = sets.find(set => set.workSetId === request.requestId);
    if (!set) { set = agentWorkSetFixture({ workSetId: request.requestId, conversationId: receipt.conversationId, requestId: receipt.requestId, workspaceId: receipt.workspaceId, repositoryId: receipt.repositoryId, sourceCheckpointId: receipt.after!.checkpointId, sourceContextSha256: receipt.sourceContextSha256, kind: request.kind, tasks: request.tasks.map((task, index) => ({ ...task, conversationId: `dddddddd-dddd-4ddd-8ddd-ddddddddddd${index}`, requestId: task.taskId, state: "queued", workspaceId: `eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee${index}`, repositoryId: `candidate-${index}`, afterCheckpointId: receipt.after!.checkpointId, detail: "The candidate waits in the queue." })) }); sets.push(set); }
    if (loseOnce && !lost) { lost = true; return route.abort("failed"); } return route.fulfill({ json: set });
  });
  await page.route("**/api/v1/agent-work-sets/**", async route => {
    const parts = new URL(route.request().url()).pathname.split("/"); const set = sets.find(set => set.workSetId === parts[4])!; expect(set).toBeTruthy();
    if (route.request().method() === "GET") return route.fulfill({ json: set });
    expect(parts[5]).toBe("items"); expect(parts[7]).toBe("cancel"); const request = route.request().postDataJSON(); cancels.push({ setId: set.workSetId, taskId: parts[6], request }); expect(request.expectedRevision).toBe(set.revision); set.revision++; set.lastMutationRequestId = request.requestId; set.tasks.find(task => task.taskId === parts[6])!.state = "cancelled"; return route.fulfill({ json: set });
  });
  return { sets, creates, cancels };
}
async function openPlan(page: Page) { await page.getByRole("button", { name: "Review changes", exact: true }).click(); const dialog = page.getByRole("dialog", { name: "Task changes", exact: true }); await dialog.getByText("Tasks and alternatives", { exact: true }).click(); return dialog.getByRole("region", { name: "Tasks and alternatives", exact: true }); }
async function fillAlternative(plan: ReturnType<Page["getByRole"]>) {
  await plan.getByRole("radio", { name: "Alternatives", exact: true }).check();
  await plan.getByRole("textbox", { name: "Task title 1", exact: true }).fill("Compact layout"); await plan.getByRole("textbox", { name: "Task prompt 1", exact: true }).fill("Keep more code visible.");
  await plan.getByRole("textbox", { name: "Task title 2", exact: true }).fill("Roomy layout"); await plan.getByRole("textbox", { name: "Task prompt 2", exact: true }).fill("Use larger controls.");
}
test("a saved plan starts exact alternatives and reviews only the chosen candidate", async ({ page, feedbackOrigin }, testInfo) => {
  await page.setViewportSize({ width: 375, height: 640 }); const fixture = await mountFeedback(page, feedbackOrigin, { review: receipt }); const state = await plans(page); const plan = await openPlan(page); await fillAlternative(plan); expect(state.creates).toEqual([]);
  await plan.getByRole("button", { name: "Start alternatives" }).dblclick({ delay: 60 }); await expect(plan.getByRole("article", { name: "Task 1: Compact layout" })).toBeVisible(); expect(state.creates).toHaveLength(1); expect(state.creates[0]).toMatchObject({ expectedAfterCheckpointId: receipt.after!.checkpointId, kind: "alternatives", tasks: [expect.objectContaining({ dependsOn: [] }), expect.objectContaining({ dependsOn: [] })] });
  const set = state.sets[0]; const task = set.tasks[0]; task.state = "completed"; set.revision++;
  await plan.getByRole("button", { name: "Refresh plans" }).click(); const row = plan.getByRole("article", { name: "Task 1: Compact layout" });
  await row.getByRole("button", { name: "Open live preview" }).click(); await expect(row.getByRole("alert")).toContainText("WTS desktop app"); await expect(row.getByRole("link", { name: "Open task workspace" })).toHaveAttribute("href", `/sessions/${task.workspaceId}/changes?repository=${task.repositoryId}`);
  const child = agentWorkChildFixture(set); const childReceipt = { ...receipt, conversationId: child.conversationId, requestId: task.requestId, workspaceId: child.workspaceId, repositoryId: child.repositoryId, patch: receipt.patch.replaceAll("title", "candidateTitle") };
  await page.route(`**/api/v1/agent-conversations/${child.conversationId}`, route => route.fulfill({ json: child }));
  await page.route(`**/api/v1/agent-conversations/${child.conversationId}/messages/${task.requestId}/changes`, route => route.fulfill({ json: childReceipt }));
  await page.route(`**/api/v1/agent-conversations/${child.conversationId}/messages/${task.requestId}/decisions`, route => route.fulfill({ json: agentTurnDecisionsFixture({ conversationId: child.conversationId, requestId: task.requestId, workspaceId: child.workspaceId, repositoryId: child.repositoryId }) }));
  await row.getByRole("button", { name: "Read task result" }).click(); const childTrigger = plan.getByRole("region", { name: "Result: Compact layout" }).getByRole("button", { name: "Review changes" }); await childTrigger.click();
  const review = page.getByRole("dialog", { name: "Compact layout changes" }); await expect(review.locator("diffs-container code")).toContainText("candidateTitle = 'New'"); await expect(review.getByRole("link", { name: "Open live preview" })).toHaveCount(0);
  const ids = await page.locator("[data-ui]").evaluateAll(elements => elements.map(element => element.getAttribute("data-ui"))); expect(new Set(ids).size).toBe(ids.length);
  await page.screenshot({ animations: "disabled", path: testInfo.outputPath("candidate-result-narrow.png") }); await page.keyboard.press("Escape"); await expect(childTrigger).toBeFocused(); await page.keyboard.press("Escape"); await expect(page.getByRole("textbox", { name: "Message to agent" })).toHaveValue(UNRELATED_DRAFT); expect(fixture.sends).toEqual([]); expect(fixture.unexpected).toEqual([]);
});
test("lost plan acknowledgement survives reload and cancellation uses that saved plan", async ({ page, feedbackOrigin }) => {
  const fixture = await mountFeedback(page, feedbackOrigin, { review: receipt }); const state = await plans(page, true); let plan = await openPlan(page); await fillAlternative(plan); await plan.getByRole("button", { name: "Start alternatives" }).click(); await expect(plan.getByRole("button", { name: "Retry task plan" })).toBeVisible(); const first = state.creates[0]; await page.reload(); plan = await openPlan(page); await expect(plan.getByRole("article", { name: "Task 1: Compact layout" })).toBeVisible(); await expect(plan.getByRole("button", { name: "Retry task plan" })).toHaveCount(0); expect(state.creates).toHaveLength(1);
  const row = plan.getByRole("article", { name: "Task 2: Roomy layout" }); await row.getByRole("button", { name: "Cancel task" }).dblclick({ delay: 60 }); await expect(row).toContainText("Cancelled"); expect(state.cancels).toEqual([{ setId: first.requestId, taskId: first.tasks[1].taskId, request: expect.objectContaining({ expectedRevision: 1 }) }]); expect((await fixture.shelf()).drafts.some(draft => draft.body === UNRELATED_DRAFT)).toBe(true); expect(fixture.sends).toEqual([]); expect(fixture.unexpected).toEqual([]);
});

test("candidate integration requires an explicit file review and keeps incomplete retry identity", async ({ page, feedbackOrigin }, testInfo) => {
  const fixture = await mountFeedback(page, feedbackOrigin, { review: receipt }); const state = await plans(page); const plan = await openPlan(page); await fillAlternative(plan); await plan.getByRole("button", { name: "Start alternatives" }).click(); await expect(plan.getByRole("article", { name: "Task 1: Compact layout" })).toBeVisible(); const set = state.sets[0]; const task = set.tasks[0]; task.state = "completed"; set.revision++; await plan.getByRole("button", { name: "Refresh plans" }).click();
  let checkBlocked = true; let applied = false; const requests: { requestId: string; effectDigest: string }[] = [];
  const effects = { schemaVersion: 1, workSetId: set.workSetId, taskId: task.taskId, workspaceId: set.workspaceId, repositoryId: set.repositoryId, sourceConversationId: set.conversationId, sourceRequestId: set.requestId, sourceAfterCheckpointId: set.sourceCheckpointId, candidateWorkspaceId: task.workspaceId, candidateConversationId: task.conversationId, candidateRequestId: task.requestId, candidateAfterCheckpointId: task.afterCheckpointId, effectDigest: `sha256:${"e".repeat(64)}`, files: [{ filePath: "src/title.ts", status: "modified" }], detail: "WTS can apply the listed file after checks pass." };
  await page.route(`**/api/v1/agent-work-sets/${set.workSetId}/items/${task.taskId}/integration-preflight`, route => route.fulfill({ json: { ...effects, state: applied ? "integrated" : checkBlocked ? "blocked" : "ready", checkRunIds: checkBlocked ? [] : ["bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"], blockers: checkBlocked ? [{ code: "noChecks", detail: "Configure checks in candidate verification." }] : [], ...(requests.length && !applied ? { resumeRequestId: requests[0].requestId } : {}) } }));
  await page.route(`**/api/v1/agent-work-sets/${set.workSetId}/items/${task.taskId}/integration`, async route => {
    const request = route.request().postDataJSON(); requests.push(request); if (requests.length > 1) expect(request).toEqual(requests[0]); applied = requests.length > 1;
    return route.fulfill({ json: { schemaVersion: 1, workSetId: set.workSetId, taskId: task.taskId, workspaceId: set.workspaceId, repositoryId: set.repositoryId, integrationRequestId: request.requestId, state: applied ? "integrated" : "incomplete", files: applied ? effects.files : [], blockers: [], detail: applied ? "WTS applied this candidate." : "The host stopped before it applied the file." } });
  });
  const row = plan.getByRole("article", { name: "Task 1: Compact layout" }); await row.getByText("Integrate candidate", { exact: true }).click(); const section = row.getByRole("region", { name: "Candidate integration" }); await expect(section.getByRole("button", { name: "Apply 1 file" })).toBeDisabled(); await expect(section.getByRole("link", { name: "Open candidate verification" })).toHaveAttribute("href", `/sessions/${task.workspaceId}/verification`); expect(requests).toEqual([]);
  checkBlocked = false; await section.getByRole("button", { name: "Refresh file effects" }).click(); await expect(section.getByText("src/title.ts", { exact: true })).toBeVisible(); expect(requests).toEqual([]); await section.getByRole("button", { name: "Apply 1 file" }).dblclick({ delay: 60 }); await expect(section.getByText("The host stopped before it applied the file.", { exact: true })).toBeVisible(); expect(requests).toHaveLength(1); const first = requests[0]; await page.reload();
  const restoredPlan = await openPlan(page); const restoredRow = restoredPlan.getByRole("article", { name: "Task 1: Compact layout" }); await restoredRow.getByText("Integrate candidate", { exact: true }).click(); const restored = restoredRow.getByRole("region", { name: "Candidate integration" }); await expect(restored.getByRole("button", { name: "Retry integration request" })).toBeEnabled(); expect(requests).toHaveLength(1); await restored.getByRole("button", { name: "Retry integration request" }).click(); await expect(restored.getByText("WTS applied this candidate.", { exact: true })).toBeVisible(); expect(requests[1]).toEqual(first); await page.screenshot({ animations: "disabled", path: testInfo.outputPath("candidate-integration.png") });
  expect(fixture.sends).toEqual([]); expect(fixture.unexpected).toEqual([]); expect((await fixture.shelf()).drafts.some(draft => draft.body === UNRELATED_DRAFT)).toBe(true);
});
